if(CMAKE_BUILD_SYSTEM_DEFINITIONS_INCLUDED)
  return()
else()
  set(CMAKE_BUILD_SYSTEM_DEFINITIONS_INCLUDED TRUE)
endif(CMAKE_BUILD_SYSTEM_DEFINITIONS_INCLUDED)


# Common Definitions
set(CMAKE_BUILD_SYSTEM_VERSION 0.0.1)
set(CBS_SYSTEM ${CMAKE_SYSTEM_NAME})
set(CBS_ARCHITECTURE ${CMAKE_SYSTEM_PROCESSOR})
set(CBS_LIB_INSTALL_PATH ${CMAKE_INSTALL_LIBDIR})
set(CBS_INCLUDE_INSTALL_PATH ${CMAKE_INSTALL_INCLUDEDIR})
