if(CMAKE_BUILD_SYSTEM_FUNCTIONS_INCLUDED)
  return()
else()
  set(CMAKE_BUILD_SYSTEM_FUNCTIONS_INCLUDED YES)
endif(CMAKE_BUILD_SYSTEM_FUNCTIONS_INCLUDED)


function(set_if_defined CHECK_VAR VAR VALUE)
  if((DEFINED CHECK_VAR) AND (DEFINED VAR) AND (DEFINED VALUE))
    if(DEFINED ${CHECK_VAR})
      set(${VAR} ${VALUE} PARENT_SCOPE)
    endif()
  endif()
endfunction(set_if_defined)

function(set_if_not_defined CHECK_VAR VAR VALUE)
  if((DEFINED CHECK_VAR) AND (DEFINED VAR) AND (DEFINED VALUE))
    if(NOT DEFINED ${CHECK_VAR})
      set(${VAR} ${VALUE} PARENT_SCOPE)
    endif()
  endif()
endfunction(set_if_not_defined)
