if(CMAKE_BUILD_SYSTEM_PACK_INCLUDED)
  return()
else()
  include(${CMAKE_BUILD_SYSTEM_DIR}/Definitions.cmake)
  set(CMAKE_BUILD_SYSTEM_PACK_INCLUDED TRUE)
endif(CMAKE_BUILD_SYSTEM_PACK_INCLUDED)


# Packing DEB
add_custom_target(pack-deb
                  COMMAND ${CMAKE_CPACK_COMMAND} -G DEB -C ${CMAKE_BUILD_TYPE})

# Packing RPM
add_custom_target(pack-rpm
                  COMMAND ${CMAKE_CPACK_COMMAND} -G RPM)

# Clear packages
add_custom_target(clear-packages
                  COMMAND rm -rf *.deb
                  COMMAND rm -rf *.rpm)


# Common
set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${CMAKE_PROJECT_VERSION}.${CBS_SYSTEM}.${CBS_ARCHITECTURE}")
set_if_defined(CBS_PACKAGE_DESCRIPTION CPACK_PACKAGE_DESCRIPTION CBS_PACKAGE_DESCRIPTION)
set_if_defined(CBS_PACKAGE_DESCRIPTION_FILE CPACK_PACKAGE_DESCRIPTION_FILE CBS_PACKAGE_DESCRIPTION_FILE)
set_if_defined(CBS_PACKAGE_DESCRIPTION_SUMMARY CPACK_PACKAGE_DESCRIPTION_SUMMARY CBS_PACKAGE_DESCRIPTION_SUMMARY)
set(CPACK_PACKAGE_VENDOR "Rodion Kolovanov")
set(CPACK_PACKAGE_CONTACT "Rodion Kolovanov")
set_if_defined(CBS_LICENSE_FILE CPACK_RESOURCE_FILE_LICENSE CBS_LICENSE_FILE)
set_if_defined(CBS_README_FILE CPACK_RESOURCE_FILE_README CBS_README_FILE})

# Debian
set(CPACK_DEB_COMPONENT_INSTALL ON)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS ON)
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE ${PROJECT_HOMEPAGE_URL})

if(CBS_PACK_DEBUG)
  set(CPACK_DEBIAN_PACKAGE_DEBUG ON)
endif()


include(CPack)
